apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: excalidraw-config
  namespace: excalidraw
spec:
  interval: 5m
  path: ./clusters/home/apps/excalidraw/excalidraw/configs/
  prune: true
  dependsOn:
    - name: excalidraw
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
