apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-ingressroute
  namespace: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
    gethomepage.dev/href: "https://home-assistant.homelab.rivetcode.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: home-assistant
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: home-assistant.png
    gethomepage.dev/app: home-assistant # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: home-assistant
    #gethomepage.dev/widget.type: "home-assistant"
    # use .local domain name so we don't get blocked by authentik
    #gethomepage.dev/widget.url: "http://home-assistant-http.home-assistant.svc.cluster.local:3000"
    gethomepage.dev/pod-selector: ""
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`home-assistant.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: home-assistant
      port: 8080
  tls:
    secretName: home-assistant-certificate-secret
