apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-cert
  namespace: home-assistant
spec:
  secretName: home-assistant-certificate-secret
  dnsNames:
    - "home-assistant.homelab.rivetcode.com"
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
