apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-setup
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/home/apps/authentik/authentik/setup/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
