---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
spec:
  encryptedData:
    password: AgCr7lYpzRx419jfXZ1YfHSgFc5JOC9a2A3G7BoSDd4vNbBSpkbumIwxrvG3EaijJTHx17kOI/BBLfCEvAPL8w9NeC5b3RI7a+l1gyG3sQ8axa891XIb61QpzyLmwwt0zH++O6FRvZFUO2EOxvbNl/unB9oi98eWoF1KbQOjE+qRs7+dlMYIGToZU+3jKuTbxGmyhWcfBdcwICRYOKxBqO1YWF+g3twXpPpaMtRGNEk+7e3bOPipf+rpnPMJ5BwclWYPfFydlSMfVNOStFkiPfVPbRSy2/AoQhZvFgh+aUJEC1DpYZxP8nurDwIogM2sLKXhXf8ANEVqBQT9hrmSr8P6StU2OerRCjsOBC4UXqLbh7pWRvRIYSJHgnUbf3FJeTUCTHMiqloJOvS33A/IhUpU3roMQHOp2KlnyZjyI70U02CSBJZQqU/jxkcD2rQZIft75x4MOetiX2uaf3D+YDvwtO7Vw9kX2Xq0BpM+EYSKgHZ+wVTC/BwCfbpZ6BuDDflI4hozKKVDYhcJ4eeh3ftU1KU0RdrU36sVoM5W2FwGJW3N6E8KfgmO4IouAeDRR0lI8HK+6DP2PyIFrK9JvSxGmeBN9xtijyou5ZWTuKsv/kMIo+RmHVNOywCtTDERNL0JqSWaWzsxOEdd6ys59LZ0z5sZ6/QRThdZaIWPJXZ5ViDHSCvBdmf++/9uwy4iUEHWAY0W4bwA1Q==
    username: AgCWa5NCEHFSSpOdlMUrJPYKo0JJq3XPY2YHGiTsKpFGWN/u5DGQoRjzGpzXeb0pkDRgd38Lf/t+qYPdE+wgtqagsYXrVXHkV2pZj+aSRyE3VK9TwQfNy+oRI7vJtxkQ7bbms6yxHyvmLO/DgERzQ43+i4cuHxcfmE6TPA1DpyVV5e0N/ZRPxFblVE5mZWrEOrhMns1jXbUZy2wG0gcxQbir9/1/ZRP+YiiZSwambELDwrkaty4pDGeSgqn+/+wVY2/NBfxC4eSHEGQGzSvDWerJWbajlq2x/S7j3UIa82iZ49Qs8FpfppD65AY54tGzmSMDR2BP8r3f3A6PaiaQSeU01LaZVsSvNbAv3HFVs2a0HB2Ho5l0LrgPA4kH/2xw7AAxUY0CYSWoXuG+rGxsYmbwSu3RahRQjT7YAdafuwGRB4mEmD2Z4E4eOrLDoznKK0reg/LWTfkwXWFE2SCFOoFHaaDPYspknX93ZUUUw/kbfjkMw6iCFw98RrT3USKkCb9BJLUZoiWPKRxsO6M97HJCwMShVwWyFBTnhJwip3fOUq8ttU4PWtJTyI0QJiib6ho5KI+qjEn1RBo+wAxWvYqG7+fbuq05gCtikFZ10HKQQ2J1aT542Kl51dXma4BmqmwmbDIFlorw3km+Og/3TCRW9JAiQXPelF7JuRGPtMM234CDwKEkgFR6jcYrsEhmKrQ15O8XZhETgQ==
  template:
    metadata:
      name: rabbitmq-secret
      namespace: rabbitmq
    type: Opaque
