apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rabbitmq-mqtt
  namespace: rabbitmq
spec:
  entryPoints:
    - mqtt
  routes:
    - match: HostSNI(`*`)  # MQTT does not use SNI by default
      services:
        - name: rabbitmq
          port: 1883
