apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vertsh.homelab.rivetcode.com
  namespace: vertsh
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
    gethomepage.dev/href: "https://vertsh.homelab.rivetcode.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Vertsh
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: mdi-file-pdf-box
    gethomepage.dev/app: vertsh # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Vertsh
    #gethomepage.dev/widget.type: "vertsh"
    #gethomepage.dev/widget.url: "https://vertsh.homelab.rivetcode.com"
    gethomepage.dev/pod-selector: ""
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`vertsh.homelab.rivetcode.com`)
      services:
        - kind: Service
          name: vertsh
          port: 80
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
  tls:
    secretName: vertsh-certificate-secret
