apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate-dependencies
  namespace: frigate
spec:
  interval: 10m
  path: ./clusters/home/apps/frigate/frigate/dependencies/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  # Skip health checks on PVC that uses local-path
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolume
      name: frigate-pv
      namespace: "" # cluster-scoped PV
    # Exclude the PVC entirely since the status will be pending until the pod leverages it
