apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate-config
  namespace: frigate
spec:
  interval: 10m
  path: ./configs/
  prune: true
  dependsOn:
    - name: frigate
      namespace: frigate
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
