apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate-dependencies
  namespace: frigate
spec:
  interval: 10m
  path: ./clusters/home/apps/frigate/frigate/dependencies/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: frigate-rtsp-secret
      namespace: frigate
