apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: excalidraw.homelab.rivetcode.com
  namespace: excalidraw
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
    gethomepage.dev/href: "https://excalidraw.homelab.rivetcode.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Excalidraw
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: mdi-application
    gethomepage.dev/app: excalidraw # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Excalidraw
    #gethomepage.dev/widget.type: "excalidraw"
    #gethomepage.dev/widget.url: "https://excalidraw.homelab.rivetcode.com"
    gethomepage.dev/pod-selector: ""
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`excalidraw.homelab.rivetcode.com`)
      services:
        - kind: Service
          name: excalidraw
          port: 80
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
  tls:
    secretName: excalidraw-certificate-secret
