apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant-config
  namespace: home-assistant
spec:
  interval: 10m
  path: ./configs/
  prune: true
  dependsOn:
    - name: home-assistant
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
