apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vertsh-config
  namespace: vertsh
spec:
  interval: 5m
  path: ./configs/
  prune: true
  dependsOn:
    - name: vertsh
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
