---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-authentik-oauth
  namespace: gitea
spec:
  encryptedData:
    key: AgCPbz8Yxo55XO9Oy8daGsKnnb+I79J/tMrVFy+WNDOiAkCdxgVnJVPrlH7ClFcuOmPeCL5GOLyuO7jrxPypw+JdHLllNdEQ7WKfzJ39vQRnLcF0dSETbkd3Z03znyqIe7FocsIJ0fIsg1Mr5szFIejiQCVIptUxLISzx3pXV+mHhcu0sohMDPfGhlMjPG/Dn+EBCvR+Ef/1EdAs8NI0OkP/0xa7R/pgPlyyhCD21oQESWX34WJ0EB+REq9EKhE3RzIMny63cKvJYB4QzV170l2XyDTmhJq2RkVng2P8xJ/q9Lsdm0hfwcgUPz1iDtMaUJSJVJ+awcKl86eQzNPqfbelqJmBZIzA7ZNYcKsnxsULpRenvfqdmkDTsLcrIwMAvSVVWRFYn1a+NZHw8BSvc1gbAWIrdoanyvBlMdY6faOhslSUGipGvYj5VdkkTPRYT6Wm/C/Q0U+oQU1nEmCDFqu2GSk7a4cRpB2rSY/UGQ1pkSwUL2ZzHzw8f7pdNVMtJ2ycfwVIYnBcq1XCYboyWKq6CGHuaZJH7TpJjPb4g/TNWrGdEioPHjbE/xZfU9BSa4vuwAcdi0vRMHoJIpiQ8pUA0MagESthKSTNnAbgkmYe3G/K78YZInx6RpHufV1zt1qONIOW/mZ1Xh9QpyNBQfSrHuekPZVBjLusoHTnZsC5QF/kIlYOJ0/NwbdDLPbdF2ifq8AGBHXBcQU9vFMbddUvCDdoB4n6di80WwDfqpBE4UAMcUPMxaQa
    secret: AgBcyXui3UypM2ZTQu9ldO4U8zWJjupK3jBlS5/1K2FefsfPo4k9B7SyEzAsyGAorNGN7euJIcZwnsYIbHdXYNs0+rrGx2KxZBBNF4ljTNj19PwYTrejdZYmGqJwucGLSWwXEOsLa4Mh+bylFnKnhKFL/VFX8thzAV+IKk72UrkdWySKFOVkZfWLqFy4fLfXYJQDWMDbJm10WLv2+IgqoVWgYuR6GKej/tSdQ6FSprPD4kJ7ugfY6sFg5N74jFBNfq66WySAhlOOihN+9LfK6oKqw/2tQaYJdLREwWaiHgU1PSBLZbO1kacpyFhCq1/VwWNStY2VAJLznqhpkkRcBgg4fOaR52l+OocCkpEWU0s+XUEBYve5n79tSBvOuRniWSl2vSn7AuGPuMxiwSFJTWZgij7rctjYFHvwgmiUnHZJr3Dl1pIf4iA8zWB+4gXRqkbJsZlcR1o3Ma1OCy23vDlHgAZXUHKl2i8O+UzJGm1SWe2AVFLbp/gtllo7uu4Iapw0TuNWICnA8WnYi+Wxd9jOgoLf/YlLzi9/36cpDKXefnEQaiiOXHqZsBI2MZvHAgDrlwepg6ehH+UHY808HZ+mjydfd0TrjXxqf4V8Y8jbfcHM5RANLM/XAhXikfJLN2T0OEfMeSo38t8CPLvggBmcVgq/Cazon3Zq9gDnzemT0jL6czaTkOcHo5QsJ8tMj5XyRuND4OnvJ+0k6cY5zRAUv3HkeZzs+8eq6qLETPZoXxjlDqYBaaWxVhni5fKftt3pdVb+9tswuAI9fztOMKilloDLOx12bfs5DhlUvxbOwTgvGYfgDFbJYz5OOiPH7F31VIWYMjwQ4v7r6z95tn1K1x27gUfFCf2kqWFJV1x0UQ==
  template:
    metadata:
      name: gitea-authentik-oauth
      namespace: gitea
    type: Opaque
