apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertsh
  namespace: vertsh
  labels:
    app.kubernetes.io/name: vertsh
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: vertsh
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vertsh
    spec:
      serviceAccountName: vertsh
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: vertsh
          image: "ghcr.io/vert-sh/vert:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
