apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kuberay-ingressroute
  namespace: kuberay-operator
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`kuberay.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: kuberay-dashboard
      port: 8265
  tls:
    secretName: kuberay-certificate-secret
