apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kuberay-clusters
  namespace: kuberay-operator
spec:
  interval: 5m
  path: ./clusters/home/apps/kuberay-operator/kuberay-operator/cluster/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
