apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frigate-cert
  namespace: frigate
spec:
  secretName: frigate-certificate-secret
  dnsNames:
    - "frigate.homelab.rivetcode.com"
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
