apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frigate-ingressroute
  namespace: frigate
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
    gethomepage.dev/href: "https://frigate.homelab.rivetcode.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Frigate
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: mdi-application
    gethomepage.dev/app: frigate # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Frigate
    gethomepage.dev/widget.type: "frigate"
    # use .local domain name so we don't get blocked by authentik
    gethomepage.dev/widget.url: "http://frigate.frigate.svc.cluster.local"
    gethomepage.dev/pod-selector: ""
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`frigate.homelab.rivetcode.com`)
    kind: Rule
    services:
    - name: frigate
      port: 5000
    middlewares:
      - name: authentik-service-middleware
        namespace: authentik
  tls:
    secretName: frigate-certificate-secret
